# Generated by Django 5.1.3 on 2024-11-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_project_userproject_up_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='up_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
