# Generated by Django 5.1.3 on 2024-11-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userproject_up_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('funcionario', 'Funcionário'), ('super', 'Gerente')], default='DEV', max_length=20),
        ),
    ]
