# Generated by Django 5.1.3 on 2024-11-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='task',
            new_name='ut_task',
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='user',
            new_name='ut_user',
        ),
    ]
